# Generated by Django 4.2.3 on 2023-07-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_category_cats_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cats',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Famous cats', 'verbose_name_plural': 'Famous cats'},
        ),
    ]
